// <auto-generated />
using System;
using APM_Back.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace APM_Back.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220511230427_WithDataSeed")]
    partial class WithDataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("APM_Back.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("text");

                    b.Property<string>("Secret")
                        .HasColumnType("text");

                    b.Property<decimal>("StarRating")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("1e429b23-acdb-418b-a8f8-fda9952f848f"),
                            Description = "Leaf rake with 48-inch wooden handle",
                            ImageUrl = "assets/images/leaf_rake.png",
                            Price = 19.95m,
                            ProductCode = "GDN-0011",
                            ProductName = "Leaf Rake",
                            ReleaseDate = "March 19, 2018",
                            StarRating = 3.2m
                        },
                        new
                        {
                            ProductId = new Guid("902e6000-f9e1-45cf-8883-98646167b8dd"),
                            Description = "15 gallon capacity rolling garden cart",
                            ImageUrl = "assets/images/garden_cart.png",
                            Price = 32.99m,
                            ProductCode = "GDN-0023",
                            ProductName = "Garden Cart",
                            ReleaseDate = "March 18, 2018",
                            StarRating = 4.2m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
