// <auto-generated />
using System;
using APM_Back.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace APM_Back.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220511232036_WithDataSeed.2")]
    partial class WithDataSeed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("APM_Back.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("text");

                    b.Property<string>("Secret")
                        .HasColumnType("text");

                    b.Property<decimal>("StarRating")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("ef0938b9-56ce-4d73-8b26-2ce33e96157f"),
                            Description = "Leaf rake with 48-inch wooden handle",
                            ImageUrl = "assets/images/leaf_rake.png",
                            Price = 19.95m,
                            ProductCode = "GDN-0011",
                            ProductName = "Leaf Rake",
                            ReleaseDate = "March 19, 2018",
                            StarRating = 3.2m
                        },
                        new
                        {
                            ProductId = new Guid("33dee5d6-ea5e-4bb4-94ba-2ee5e29fdfec"),
                            Description = "15 gallon capacity rolling garden cart",
                            ImageUrl = "assets/images/garden_cart.png",
                            Price = 32.99m,
                            ProductCode = "GDN-0023",
                            ProductName = "Garden Cart",
                            ReleaseDate = "March 18, 2018",
                            StarRating = 4.2m
                        },
                        new
                        {
                            ProductId = new Guid("3f1c8491-ff04-481a-9bb5-b62dab42d6dd"),
                            Description = "Curved claw steel hammer",
                            ImageUrl = "assets/images/hammer.png",
                            Price = 8.9m,
                            ProductCode = "TBX-0048",
                            ProductName = "Hammer",
                            ReleaseDate = "May 21, 2018",
                            StarRating = 4.8m
                        },
                        new
                        {
                            ProductId = new Guid("2d810566-e92a-450d-a6c3-7bf0bf4ac695"),
                            Description = "15-inch steel blade hand saw",
                            ImageUrl = "assets/images/saw.png",
                            Price = 11.55m,
                            ProductCode = "TBX-0022",
                            ProductName = "Saw",
                            ReleaseDate = "May 15, 2018",
                            StarRating = 3.7m
                        },
                        new
                        {
                            ProductId = new Guid("23e53b7e-3e3d-4af0-84c5-c91ff5c1a2e5"),
                            Description = "Standard two-button video game controller",
                            ImageUrl = "assets/images/xbox-controller.png",
                            Price = 35.95m,
                            ProductCode = "GMG-0042",
                            ProductName = "Video Game Controller",
                            ReleaseDate = "October 15, 2018",
                            StarRating = 4.6m
                        },
                        new
                        {
                            ProductId = new Guid("1254335b-c730-4081-964b-5c9faf23d9bc"),
                            Description = "Leaf rake with 48-inch wooden handle",
                            ImageUrl = "assets/images/leaf_rake.png",
                            Price = 19.95m,
                            ProductCode = "GDN-0011",
                            ProductName = "Leaf Rake Copied",
                            ReleaseDate = "March 19, 2018",
                            StarRating = 3.2m
                        },
                        new
                        {
                            ProductId = new Guid("be8e9481-7a33-441f-9236-0b172f3a3623"),
                            Description = "15 gallon capacity rolling garden cart",
                            ImageUrl = "assets/images/garden_cart.png",
                            Price = 32.99m,
                            ProductCode = "GDN-0023",
                            ProductName = "Garden Cart Copied",
                            ReleaseDate = "March 18, 2018",
                            StarRating = 4.2m
                        },
                        new
                        {
                            ProductId = new Guid("22e2ac8d-f2c4-4545-8aa6-cdb94bb1f8f7"),
                            Description = "Curved claw steel hammer",
                            ImageUrl = "assets/images/hammer.png",
                            Price = 8.9m,
                            ProductCode = "TBX-0048",
                            ProductName = "Hammer Copied",
                            ReleaseDate = "May 21, 2018",
                            StarRating = 4.8m
                        },
                        new
                        {
                            ProductId = new Guid("ef0d60d5-c396-40fb-8c1d-e25b8cf0aa08"),
                            Description = "15-inch steel blade hand saw",
                            ImageUrl = "assets/images/saw.png",
                            Price = 11.55m,
                            ProductCode = "TBX-0022",
                            ProductName = "Saw Copied",
                            ReleaseDate = "May 15, 2018",
                            StarRating = 3.7m
                        },
                        new
                        {
                            ProductId = new Guid("2fae6565-73db-4f06-8135-85aa36807bad"),
                            Description = "Standard two-button video game controller",
                            ImageUrl = "assets/images/xbox-controller.png",
                            Price = 35.95m,
                            ProductCode = "GMG-0042",
                            ProductName = "Video Game Controller Copied",
                            ReleaseDate = "October 15, 2018",
                            StarRating = 4.6m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
